{'Setup': {'Base': [{'AdapDegrad': 'False',
                     'ClampMode': 0,
                     'Current_Time': 6,
                     'Expanded': 'False',
                     'FrameBounds': [{'H': '2160',
                                      'SX': '32',
                                      'SY': '18',
                                      'W': '3840',
                                      'X': '0',
                                      'Y': '0'}],
                     'Frames': 0,
                     'Input_DataType': 4,
                     'NAME': 'Timewarp',
                     'NoMediaHandling': 1,
                     'Note': [{}],
                     'Range': [{'After': '1',
                                'Before': '1',
                                'Enable': 'False',
                                'End': '35',
                                'Span': '100',
                                'SpanEnable': 'False',
                                'Start': '1'}],
                     'ReadOnly': 'False',
                     'RenderingMode': 0,
                     'ScrollBar': 0,
                     'UsedAsTransition': 'False',
                     'Version': 20}],
           'State': [{'TW_Anchor': 1,
                      'TW_AnchorOffset': 0,
                      'TW_BlurPhase': 0,
                      'TW_BlurRefColor': [{'A': 1, 'B': 0, 'G': 0, 'R': 1}],
                      'TW_BlurSamplesChannel': [{'Channel': [{'Name': 'Samples'}]}],
                      'TW_BlurShutterChannel': [{'Channel': [{'Name': 'Shutter'}]}],
                      'TW_DisplaySpeedFPS': 'False',
                      'TW_DoBlur': 'False',
                      'TW_DoBlurReference': 'False',
                      'TW_DurationTiming': [{'Channel': [{'Extrap': 'linear',
                                                          'KFrames': [{'Key': [{'CurveMode': 'bezier',
                                                                                'CurveOrder': 'cubic',
                                                                                'Frame': 1,
                                                                                'Index': '0',
                                                                                'LAutoSlope': 'False',
                                                                                'LHandle_dX': -0.25,
                                                                                'LHandle_dY': -0.25,
                                                                                'RAutoSlope': 'False',
                                                                                'RHandle_dX': 0.25,
                                                                                'RHandle_dY': 0.25,
                                                                                'TangentMode': 'manual',
                                                                                'Value': 1},
                                                                               {'CurveMode': 'bezier',
                                                                                'CurveOrder': 'cubic',
                                                                                'Frame': 36,
                                                                                'Index': '1',
                                                                                'LAutoSlope': 'False',
                                                                                'LHandle_dX': -0.25,
                                                                                'LHandle_dY': -0.25,
                                                                                'RAutoSlope': 'False',
                                                                                'RHandle_dX': 0.25,
                                                                                'RHandle_dY': 0.25,
                                                                                'TangentMode': 'manual',
                                                                                'Value': 36}]}],
                                                          'KeyVersion': 2,
                                                          'Name': 'durationTiming',
                                                          'Size': 2,
                                                          'Value': 36}]}],
                      'TW_FieldInterpMode': 0,
                      'TW_FlowQuality': 2,
                      'TW_FrameMode': 2,
                      'TW_GlobalMotionResolution': [{'Channel': [{'Name': 'GlobalMotionResolution'}]}],
                      'TW_GlobalMotionSmoothness': [{'Channel': [{'Name': 'GlobalMotionSmoothness'}]}],
                      'TW_LockMode': 0,
                      'TW_Mix': [{'Channel': [{'Name': 'MixAmount'}]}],
                      'TW_PostTrail': [{'Channel': [{'Name': 'Post'}]}],
                      'TW_PostWeight': [{'Channel': [{'Name': 'Post'}]}],
                      'TW_PreTrail': [{'Channel': [{'Name': 'Pre'}]}],
                      'TW_PreWeight': [{'Channel': [{'Name': 'Pre'}]}],
                      'TW_ReferencePointX': [{'Channel': [{'Name': 'X'}]}],
                      'TW_ReferencePointY': [{'Channel': [{'Name': 'Y'}]}],
                      'TW_Regen': 'True',
                      'TW_RepeatMode': 1,
                      'TW_RetimerMode': 0,
                      'TW_SamplingMode': 0,
                      'TW_Speed': [{'Channel': [{'Extrap': 'constant',
                                                 'KFrames': [{'Key': [{'CurveMode': 'hermite',
                                                                       'CurveOrder': 'linear',
                                                                       'Frame': 1,
                                                                       'Index': '0',
                                                                       'LHandle_dX': -6.333333,
                                                                       'LHandle_dY': 0,
                                                                       'RHandle_dX': 6.333333,
                                                                       'RHandle_dY': 0,
                                                                       'Value': 20},
                                                                      {'CurveMode': 'hermite',
                                                                       'CurveOrder': 'linear',
                                                                       'Frame': 20,
                                                                       'Index': '1',
                                                                       'LHandle_dX': -6.333333,
                                                                       'LHandle_dY': -10.857143,
                                                                       'RHandle_dX': 5.333333,
                                                                       'RHandle_dY': 9.142858,
                                                                       'Value': 120},
                                                                      {'CurveMode': 'hermite',
                                                                       'CurveOrder': 'linear',
                                                                       'Frame': 36,
                                                                       'Index': '2',
                                                                       'LHandle_dX': -0.25,
                                                                       'LHandle_dY': 0,
                                                                       'RHandle_dX': 0.25,
                                                                       'RHandle_dY': 0,
                                                                       'Value': 80}]}],
                                                 'KeyVersion': 2,
                                                 'Name': 'Speed',
                                                 'Size': 3,
                                                 'Value': 46.3157883}]}],
                      'TW_SpeedTiming': [{'Channel': [{'Extrap': 'linear',
                                                       'KFrames': [{'Key': [{'CurveMode': 'hermite',
                                                                             'CurveOrder': 'quadratic',
                                                                             'Frame': 1,
                                                                             'Index': '0',
                                                                             'LAutoSlope': 'False',
                                                                             'LHandle_dX': -0.25,
                                                                             'LHandle_dY': -0.05,
                                                                             'RAutoSlope': 'False',
                                                                             'RHandle_dX': 0.25,
                                                                             'RHandle_dY': 0.05,
                                                                             'TangentMode': 'manual',
                                                                             'Value': 1},
                                                                            {'CurveMode': 'hermite',
                                                                             'CurveOrder': 'quadratic',
                                                                             'Frame': 20,
                                                                             'Index': '1',
                                                                             'LAutoSlope': 'False',
                                                                             'LHandle_dX': -0.25,
                                                                             'LHandle_dY': -0.3,
                                                                             'RAutoSlope': 'False',
                                                                             'RHandle_dX': 0.25,
                                                                             'RHandle_dY': 0.3,
                                                                             'TangentMode': 'manual',
                                                                             'Value': 14.2999992},
                                                                            {'CurveMode': 'hermite',
                                                                             'CurveOrder': 'quadratic',
                                                                             'Frame': 36,
                                                                             'Index': '2',
                                                                             'LAutoSlope': 'False',
                                                                             'LHandle_dX': -0.25,
                                                                             'LHandle_dY': -0.2,
                                                                             'RAutoSlope': 'False',
                                                                             'RHandle_dX': 0.25,
                                                                             'RHandle_dY': 0.2,
                                                                             'TangentMode': 'manual',
                                                                             'Value': 30.2999992}]}],
                                                       'KeyVersion': 2,
                                                       'Name': 'SpeedTiming',
                                                       'Size': 3,
                                                       'Value': 1}]}],
                      'TW_StrobeRepeat': 1,
                      'TW_Timing': [{'Channel': [{'Extrap': 'linear',
                                                  'KFrames': [{'Key': [{'CurveMode': 'hermite',
                                                                        'CurveOrder': 'linear',
                                                                        'Frame': 1,
                                                                        'Index': '0',
                                                                        'LHandle_dX': -0.25,
                                                                        'LHandle_dY': -0.25,
                                                                        'RHandle_dX': 0.25,
                                                                        'RHandle_dY': 0.25,
                                                                        'Value': 1}]}],
                                                  'KeyVersion': 2,
                                                  'Name': 'Timing',
                                                  'Size': 1,
                                                  'Value': 6}]}]}]}}
